
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Navbar from "../../components/Navbar";
import localFont from "next/font/local";
import SessionAuthProvider from "@/components/SessionAuthProvider";
import CleanFacebookHash from "@/components/CleanFacebookHash";
import { ReactNode } from "react";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import CartSyncManager from "@/components/CartSyncManager";
import WishlistSyncManager from "@/components/WishlistSyncManager";
import ProductsSyncManager from "@/components/ProductsSyncManager";
import CartPreview from "@/components/cartComponents/CartPreview";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const playFairDisplay = localFont({
  src: [
    {
      path: './fonts/PlayfairDisplay-Regular.ttf',
      weight: '100 900', // full weight range
      style: 'normal',
    },
  ],
  variable: '--font-play-fair',
  display: 'swap',
});

const DMSans_semiBold = localFont({
  src: [
    {
      path: './fonts/DMSans_18pt-SemiBold.ttf',
    },
  ],
  variable: '--font-dm-sans-semibold',
  display: 'swap',
});
const DMSans_Light = localFont({
  src: [
    {
      path: './fonts/DMSans-Light.ttf',
    },
  ],
  variable: '--font-dm-sans-light',
  display: 'swap',
});
const DMSans_regular = localFont({
  src: [
    {
      path: './fonts/DMSans-Regular.ttf',
    },
  ],
  variable: '--font-dm-sans-regular',
  display: 'swap',
});
const monasans_semibold = localFont({
  src: [
    {
      path: './fonts/MonaSans_SemiExpanded-SemiBold.ttf',
    },
  ],
  variable: '--font-monasans-semibold',
  display: 'swap',
});
const DMSans_italic_light = localFont({
  src: [
    {
      path: './fonts/DMSans_18pt-LightItalic.ttf',
    },
  ],
  variable: '--font-dm-sans-italic-light',
  display: 'swap',
});
const monasans_bold = localFont({
  src: [
    {
      path: './fonts/MonaSans-Black.ttf',
    },
  ],
  variable: '--font-monasans-black',
  display: 'swap',
});


export default function RootLayout({ children }: { children: ReactNode }) {


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playFairDisplay.variable} ${DMSans_semiBold.variable} ${DMSans_Light.variable} ${DMSans_regular.variable} ${monasans_semibold.variable}  ${DMSans_italic_light.variable} ${monasans_bold.variable} antialiased bg-[#ffffff]`}
      >


        <SessionAuthProvider>

          <Navbar />
          {/* <CategoriesBar /> */}
          <CleanFacebookHash />
          <CartSyncManager />
          <WishlistSyncManager />
          <ProductsSyncManager />
          <CartPreview />
          <main className="min-h-screen">
            {children}
          </main>
          <ToastContainer
            position="bottom-center"
            autoClose={3000}
            closeOnClick
            pauseOnHover
            draggable
            toastClassName="!rounded-xl !px-4 !py-2 !text-sm font-dmsans_medium sm:!px-6 sm:!py-3 sm:!text-base"
            className="!w-[90vw] sm:!w-auto"
          />

          <Footer />
        </SessionAuthProvider>


      </body>
    </html>
  );
}

