import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Navbar";
import { CartProvider } from "./contexts/CartContext";
import { AuthProvider } from "./contexts/AuthContext";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const playFairDisplay = localFont({
  src: [
    {
      path: './fonts/PlayfairDisplay-VariableFont_wght.ttf',
      weight: '100 900', // full weight range
      style: 'normal',
    },
  ],
  variable: '--font-play-fair',
  display: 'swap',
});

const playFairDisplay2 = localFont({
  src: [
    {
      path: './fonts/PlayfairDisplay-Regular.ttf',
    },
  ],
  variable: '--font-play-fair-2',
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playFairDisplay.variable} ${playFairDisplay2.variable} antialiased`}
      >
        <AuthProvider>
          <CartProvider>
            <Navbar />
            <main className="min-h-screen">{children}</main>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}

