const items = [
  {
    namee: "Strawberry",
    id: 3,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Fragaria",
    image: "https://upload.wikimedia.org/wikipedia/commons/2/29/PerfectStrawberry.jpg",
    nutritions: {
      calories: 29.0,
      fat: 0.4,
      sugar: 5.4,
      carbohydrates: 5.5,
      protein: 0.8,
    },
    price: 4.99,
  },
  {
    namee: "Banana",
    id: 1,
    family: "Musaceae",
    order: "Zingiberales",
    genus: "Musa",
    image: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Banana-Single.jpg",
    nutritions: {
      calories: 96.0,
      fat: 0.2,
      sugar: 17.2,
      carbohydrates: 22.0,
      protein: 1.0,
    },
    price: 1.29,
  },
  {
    namee: "Tomato",
    id: 5,
    family: "Solanaceae",
    order: "Solanales",
    genus: "Solanum",
    image: "https://upload.wikimedia.org/wikipedia/commons/8/88/Bright_red_tomato_and_cross_section02.jpg",
    nutritions: {
      calories: 74.0,
      fat: 0.2,
      sugar: 2.6,
      carbohydrates: 3.9,
      protein: 0.9,
    },
    price: 2.49,
  },
  {
    namee: "Blackberry",
    id: 64,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Rubus",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaPnzAOc8-YUw02uqhiNCwq8lge4DFhHJbLg&s",
    nutritions: {
      calories: 40.0,
      fat: 0.4,
      sugar: 4.5,
      carbohydrates: 9.0,
      protein: 1.3,
    },
    price: 5.49,
  },
  {
    namee: "Kiwi",
    id: 66,
    family: "Actinidiaceae",
    order: "Ericales",
    genus: "Actinidia",
    image: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Kiwi_aka.jpg",
    nutritions: {
      calories: 61.0,
      fat: 0.5,
      sugar: 9.0,
      carbohydrates: 15.0,
      protein: 1.1,
    },
    price: 3.99,
  },
  {
    namee: "Pineapple",
    id: 10,
    family: "Bromeliaceae",
    order: "Poales",
    genus: "Ananas",
    image: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Pineapple_and_cross_section.jpg",
    nutritions: {
      calories: 50.0,
      fat: 0.12,
      sugar: 9.85,
      carbohydrates: 13.12,
      protein: 0.54,
    },
    price: 2.99,
  },
  {
    namee: "Plum",
    id: 71,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Prunus",
    image: "https://media.istockphoto.com/id/1388174145/photo/plum-isolated-on-white.jpg?s=612x612&w=0&k=20&c=fdUpkfAtlTrpDgm_N66OXE63NbS8RrCnPcblSFQ8kcE=",
    nutritions: {
      calories: 46.0,
      fat: 0.28,
      sugar: 9.92,
      carbohydrates: 11.4,
      protein: 0.7,
    },
    price: 2.79,
  },
  {
    namee: "Orange",
    id: 2,
    family: "Rutaceae",
    order: "Sapindales",
    genus: "Citrus",
    image: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Orange-Fruit-Pieces.jpg",
    nutritions: {
      calories: 43.0,
      fat: 0.2,
      sugar: 8.2,
      carbohydrates: 8.3,
      protein: 1.0,
    },
    price: 1.99,
  },
  {
    namee: "GreenApple",
    id: 72,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Malus",
    image: "https://www.urbangroc.com/wp-content/uploads/2023/01/pngwing.com_.png.webp",
    nutritions: {
      calories: 21.0,
      fat: 0.1,
      sugar: 6.4,
      carbohydrates: 3.1,
      protein: 0.4,
    },
    price: 2.49,
  },
  {
    namee: "Watermelon",
    id: 25,
    family: "Cucurbitaceae",
    order: "Cucurbitales",
    genus: "Citrullus",
    image: "https://farmtodoorstep.co/wp-content/uploads/2020/05/watermelon.jpg",
    nutritions: {
      calories: 30.0,
      fat: 0.2,
      sugar: 6.0,
      carbohydrates: 8.0,
      protein: 0.6,
    },
    price: 1.49,
  },
  {
    namee: "Lemon",
    id: 26,
    family: "Rutaceae",
    order: "Sapindales",
    genus: "Citrus",
    image: "https://media.istockphoto.com/id/1406047398/photo/lemon-with-leaf-isolated-on-white-background.jpg?s=612x612&w=0&k=20&c=WIwBPye17pFzllBxa4qRvwprxFTAS5S3nJyDvmm49ok=",
    nutritions: {
      calories: 29.0,
      fat: 0.3,
      sugar: 2.5,
      carbohydrates: 9.0,
      protein: 1.1,
    },
    price: 2.29,
  },
  {
    namee: "Mango",
    id: 27,
    family: "Anacardiaceae",
    order: "Sapindales",
    genus: "Mangifera",
    image: "https://5.imimg.com/data5/SELLER/Default/2023/9/344928632/OW/RQ/XC/25352890/yellow-mango.jpeg",
    nutritions: {
      calories: 60.0,
      fat: 0.38,
      sugar: 13.7,
      carbohydrates: 15.0,
      protein: 0.82,
    },
    price: 3.29,
  },
  {
    namee: "Blueberry",
    id: 33,
    family: "Ericaceae",
    order: "Ericales",
    genus: "Vaccinium",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7gtwQgG9N46nxxpG-o82Vu6ZLMookYmhOYQ&s",
    nutritions: {
      calories: 57.0,
      fat: 0.3,
      sugar: 10.0,
      carbohydrates: 14.5,
      protein: 0.7,
    },
    price: 5.99,
  },
  {
    namee: "Apple",
    id: 6,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Malus",
    image: "https://upload.wikimedia.org/wikipedia/commons/1/15/Red_Apple.jpg",
    nutritions: {
      calories: 52.0,
      fat: 0.4,
      sugar: 10.3,
      carbohydrates: 11.4,
      protein: 0.3,
    },
    price: 2.49,
  },
  {
    namee: "Guava",
    id: 37,
    family: "Myrtaceae",
    order: "Myrtales",
    genus: "Psidium",
    image: "https://orgfarm.store/cdn/shop/files/guava.webp?v=1721811540",
    nutritions: {
      calories: 68.0,
      fat: 1.0,
      sugar: 9.0,
      carbohydrates: 14.0,
      protein: 2.6,
    },
    price: 3.79,
  },
];

export default items;
